---
- set_fact:
    arch: linux_amd64
  when: ansible_system == "Linux"

- set_fact:
    arch: darwin_amd64
  when: ansible_system == "Darwin"

- name: Create vault group
  group: >
    name={{vault.group}} system=yes state=present

- name: Create vault user
  user: >
    name={{vault.user}} group={{vault.group}} system=yes
    home=/var/lib/vault shell=/bin/false
    state=present

- name: install unzip from yum
  yum:
    name: unzip
    state: latest
  when: rhel_centos_7

- name: Unpacks OSS to location
  unarchive: >
    src={{ download_url}}/{{vault.name}}/{{ vault.version }}/{{vault.name}}_{{ vault.version }}_{{ arch }}.zip
    dest={{ dir.install }}
    copy=yes
    owner={{ vault.user }}
    group={{ vault.group }}
    validate_certs=yes
    mode=0750
  when: not "{{enterprise}}"

- name: copy certificates to config directory
  copy: src={{item}} dest={{dir_config}} owner={{vault.user}} group={{vault.group}} mode=0600
  with_items: 
    - "vault.crt"
    - "ca/root_vault.pem"

- name: copy key file to config directory
  copy: content={{vault_tls_key}} dest={{dir_config}}/vault.key owner={{vault.user}} group={{vault.group}} mode=0600

- name: copy cert file to config directory
  copy: content={{vault_tls_cert}} dest={{dir_config}}/vault.crt owner={{vault.user}} group={{vault.group}} mode=0600

- name: copy cert file to config directory
  copy: content={{vault_tls_ca_cert}} dest={{dir_config}}/root_vault.pem owner={{vault.user}} group={{vault.group}} mode=0600

- name: Create Vault configuration file
  template: >
    src=vault.hcl.j2
    dest={{ dir_config }}/vault.hcl
    owner={{ vault.user }}
    group={{ vault.group }}
    mode=0600
  notify: 
    - restart vault

- include: service.rh6.yml
  when: rhel_centos_6

- include: service.rh7.yml
  when: rhel_centos_7

- name: Give vault access to mlock syscall
  capabilities: >
    path={{ dir.install }}/vault
    capability='cap_ipc_lock=+ep'
    state=present

- name: Ensure Vault service is started and enabled at boot
  service: name=vault state=started enabled=yes