---
# Vault needs to be initialized only once for an active/standby configuration

- set_fact:
    init_keys_token: "{{ lookup('file', unseal_keys_location)|from_json }}"
  when: not "{{enterprise}}"

- name: Start Vault service 
  service: name=vault state=restarted

- name: Unseal vault
  uri: 
    url: https://127.0.0.1:8200/v1/sys/unseal
    method: PUT
    body: '{"key":"{{item}}"}'
    body_format: json
    validate_certs: yes
    return_content: yes
  with_items: "{{init_keys_token['keys']|default([])}}"
  run_once: true
  no_log: true
  when: not "{{enterprise}}"
